version: '3.7'
services:
  portfolio01-mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
  portfolio01-express:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./src/:/portfolio01/backend/src
      - ./swagger/:/portfolio01/backend/swagger
    ports:
      - 3000:3000